from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


print(User.objects.all())